# Generated by Django 2.2.9 on 2020-02-04 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewed_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='goods.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='review',
            field=models.ManyToManyField(through='goods.Review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.ItemType'),
        ),
    ]
