# Generated by Django 2.2.9 on 2020-01-26 11:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200126_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemtype',
            options={'verbose_name': 'категория товара', 'verbose_name_plural': 'категории товара'},
        ),
        migrations.AddField(
            model_name='item',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 26, 11, 9, 30, 398276, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='name_slug',
            field=models.CharField(default='djangodbmodelsfieldscharfield', max_length=64),
        ),
    ]
