# Generated by Django 2.2.9 on 2020-02-12 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200206_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemtype',
            old_name='name',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='itemtype',
            old_name='item_type',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='reviewed_item',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='item',
            name='review',
        ),
    ]
