# Generated by Django 2.2.9 on 2020-01-26 11:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20200126_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 26, 11, 30, 4, 473634, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
