# Generated by Django 2.2.9 on 2020-02-04 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20200204_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='review',
            field=models.ManyToManyField(related_name='items', through='goods.Review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewed_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='goods.Item'),
        ),
    ]
