# Generated by Django 2.2.9 on 2020-01-26 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20200126_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
