# Generated by Django 2.2.9 on 2020-01-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20200126_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name_slug',
            field=models.SlugField(),
        ),
    ]
