# Generated by Django 2.2.9 on 2020-02-05 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20200205_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='goods.OrderPosition', to='goods.Item'),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Item'),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
