# Generated by Django 2.2.9 on 2020-02-04 13:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'предложение', 'verbose_name_plural': 'предложения'},
        ),
        migrations.AlterField(
            model_name='offer',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.ItemType', verbose_name='товары'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='headline',
            field=models.CharField(max_length=200, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='sub_line',
            field=models.CharField(max_length=300, verbose_name='саблайн'),
        ),
    ]
